# Data Preparation

## Data Load

In [1]:
import pandas as pd
import numpy as np

In [2]:
file_in = "df_amazon_original.csv"
file_out = "df_processed.csv"

In [3]:
df = pd.read_csv(file_in)

In [4]:
df.head()

,Unnamed: 0,_id,Unnamed: 2,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,ProductURL
0,0,660136d21ab34c5dcc314932,3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...,https://www.amazon.com/dp/B000UA0QIQ
1,1,660136d21ab34c5dcc314934,6,7,B006K2ZZ7K,A1SP2KVKFXXRU1,David C. Sullivan,0,0,5,1340150400,Great! Just as good as the expensive brands!,This saltwater taffy had great flavors and was...,https://www.amazon.com/dp/B006K2ZZ7K
2,2,660136d21ab34c5dcc314935,7,8,B006K2ZZ7K,A3JRGQVEQN31IQ,Pamela G. Williams,0,0,5,1336003200,"Wonderful, tasty taffy",This taffy is so good. It is very soft and ch...,https://www.amazon.com/dp/B006K2ZZ7K
3,3,660136d21ab34c5dcc314938,9,10,B00171APVA,A21BT40VZCCYT4,Carol A. Reed,0,0,5,1351209600,Healthy Dog Food,This is a very healthy dog food. Good for thei...,https://www.amazon.com/dp/B00171APVA
4,4,660136d21ab34c5dcc31493d,13,14,B001GVISJM,A18ECVX2RJ7HUE,"willie ""roadie""",2,2,4,1288915200,fresh and greasy!,good flavor! these came securely packed... the...,https://www.amazon.com/dp/B001GVISJM

## Processing

In [5]:
df.replace({None: np.nan}, inplace=True)
# df = df.set_index("").reset_index(drop=True).drop('_id',axis=1)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Unnamed: 0              568454 non-null  int64
 1   _id                     568454 non-null  object
 2   Unnamed: 2              568454 non-null  int64
 3   Id                      568454 non-null  int64
 4   ProductId               568454 non-null  object
 5   UserId                  568454 non-null  object
 6   ProfileName             568406 non-null  object
 7   HelpfulnessNumerator    568454 non-null  int64
 8   HelpfulnessDenominator  568454 non-null  int64
 9   Score                   568454 non-null  int64
 10  Time                    568454 non-null  int64
 11  Summary                 568425 non-null  object
 12  Text                    568454 non-null  object
 13  ProductURL              568454 non-null  object
dtypes: int64(7), object(7)
memory usage: 60.7+ MB

In [7]:
# Null values
df.isna().sum()

Unnamed: 0                 0
_id                        0
Unnamed: 2                 0
Id                         0
ProductId                  0
UserId                     0
ProfileName               48
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   29
Text                       0
ProductURL                 0
dtype: int64

In [8]:
df[df.isna().any(axis=1)]

,Unnamed: 0,_id,Unnamed: 2,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,ProductURL
10441,10441,660136e31ab34c5dcc3172a7,10616,10617,B002DHN956,A1LSYR30XW7CFT,NaN,1,2,5,1291680000,Awesome,This is 72 for the price of like 24 at the gro...,https://www.amazon.com/dp/B002DHN956
25605,25605,660136f71ab34c5dcc31acd4,25509,25510,B000LKZB4Y,A36BVYD0NT7Z0F,NaN,0,0,5,1314576000,These are the best mints and no aspartame or BHT,I was so shocked to find out that almost all g...,https://www.amazon.com/dp/B000LKZB4Y
29270,29270,660136fd1ab34c5dcc31baa0,29042,29043,B000MPRP4C,A1DJV0XTCCSZ8F,NaN,0,0,5,1342915200,Best tea ever,"Addicted to this bright, strong tea for breakf...",https://www.amazon.com/dp/B000MPRP4C
33844,33844,660137061ab34c5dcc31cdd5,33958,33959,B00412W76S,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...,https://www.amazon.com/dp/B00412W76S
38891,38891,6601370b1ab34c5dcc31e109,38874,38875,B000AYDGZ2,A36BVYD0NT7Z0F,NaN,2,3,1,1278374400,doesn't anyone care that they are putting BHT ...,I called Kellogg's to see why Special K red be...,https://www.amazon.com/dp/B000AYDGZ2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522150,522150,66013b201ab34c5dcc394116,522215,522216,B001D9YVE8,A20DJISCACLF8J,NaN,1,2,5,1231286400,great tea,I love this tea! A lot of green teas are too ...,https://www.amazon.com/dp/B001D9YVE8
530565,530565,66013b371ab34c5dcc39624a,530716,530717,B0014ATRV8,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...,https://www.amazon.com/dp/B0014ATRV8
537417,537417,66013b491ab34c5dcc397c7e,537423,537424,B0034EFIYC,AOZHN8BHN0Y1O,NaN,0,0,5,1348099200,Walnut and date,These were the best nutrient bars I have had E...,https://www.amazon.com/dp/B0034EFIYC
539788,539788,66013b4c1ab34c5dcc39858b,539740,539741,B000FIXYB4,A1DJV0XTCCSZ8F,NaN,0,0,4,1271030400,We like it,"Good portion size (7.5 oz), not too carb-heavy...",https://www.amazon.com/dp/B000FIXYB4
560573,560573,66013b801ab34c5dcc39d66d,560446,560447,B000CQID1K,AGT3BYX5P9SLH,NaN,0,0,5,1324684800,awesome,i love them they are amazing I would eat them ...,https://www.amazon.com/dp/B000CQID1K

In [9]:
# Drop Na
df = df.dropna()

In [10]:
# Check for Duplicates
df.duplicated().sum()

0

## Change data type

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 568377 entries, 0 to 568453
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Unnamed: 0              568377 non-null  int64
 1   _id                     568377 non-null  object
 2   Unnamed: 2              568377 non-null  int64
 3   Id                      568377 non-null  int64
 4   ProductId               568377 non-null  object
 5   UserId                  568377 non-null  object
 6   ProfileName             568377 non-null  object
 7   HelpfulnessNumerator    568377 non-null  int64
 8   HelpfulnessDenominator  568377 non-null  int64
 9   Score                   568377 non-null  int64
 10  Time                    568377 non-null  int64
 11  Summary                 568377 non-null  object
 12  Text                    568377 non-null  object
 13  ProductURL              568377 non-null  object
dtypes: int64(7), object(7)
memory usage: 65.0+ MB

In [12]:
# Date to datetime
df['Time'] = pd.to_datetime(df['Time'], unit='s')
# Object to String
df['Summary'] = df['Summary'].astype('string')
df['Text'] = df['Text'].astype('string')

In [13]:
df['Year'] = df['Time'].dt.year
df['Month'] = df['Time'].dt.month
df['Day'] = df['Time'].dt.day

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 568377 entries, 0 to 568453
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Unnamed: 0              568377 non-null  int64
 1   _id                     568377 non-null  object
 2   Unnamed: 2              568377 non-null  int64
 3   Id                      568377 non-null  int64
 4   ProductId               568377 non-null  object
 5   UserId                  568377 non-null  object
 6   ProfileName             568377 non-null  object
 7   HelpfulnessNumerator    568377 non-null  int64
 8   HelpfulnessDenominator  568377 non-null  int64
 9   Score                   568377 non-null  int64
 10  Time                    568377 non-null  datetime64[ns]
 11  Summary                 568377 non-null  string
 12  Text                    568377 non-null  string
 13  ProductURL              568377 non-null  object
 14  Year                    568377 non-null  int32
 15  Month                   568377 non-null  int32
 16  Day                     568377 non-null  int32
dtypes: datetime64[ns](1), int32(3), int64(6), object(5), string(2)
memory usage: 71.6+ MB

## Data out

In [15]:
df.to_csv(file_out)